# adapted from https://gist.github.com/jonasbn/fecdb0efdd9cfb45ebe0
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:

   # Prevent "Please tell me who you are" errors for certain DZIL configs
   - git config --global user.name "TravisCI"

install:

   # Deal with all of the DZIL dependencies, quickly and quietly
   - cpanm --quiet --notest Dist::Zilla

   # Hack to getting the latest Test::Kwalitee
   - cpanm --quiet --notest Test::Kwalitee

   # Getting coveralls report
   - cpanm --quiet --notest Devel::Cover::Report::Coveralls

   # Getting cover command for Dist::Zilla
   - cpanm --quiet --notest Dist::Zilla::App::Command::cover

   # Getting all the plugins used by Dist::Zilla in this particular setup
   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest

   # Getting all the dependencies requested by author
   - dzil listdeps --author | cpanm --quiet --notest
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

   # Getting all the dependencies requested by distribution
   - dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest

script:

   - dzil smoke --release --author

after_success:

    - dzil cover -outputdir cover_db -report coveralls
